{
 "title": "RTLSDR Airband Monitor",
 "description": "RTLSDR-Airband OA6DXV ver. | Activity, Noise and Signal level monitor ",
 "tags": [
  "rtl-airband",
  "rtl_airband",
  "airband",
  "sdr"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Noise Level (dBFS)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dBFS_noise_level{}", "legendFormat": "{{freq}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "channel_activity_counter{}", "legendFormat": "{{freq}}" }
   ]
  },
  {
   "title": "Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(channel_activity_counter{}[30s])",
     "legendFormat": "{{freq}}"
    }
   ]
  },
  {
   "title": "Noise Level",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dBFS" } },
   "targets": [
    { "expr": "dBFS_noise_level{}", "legendFormat": "{{freq}}" }
   ]
  },
  {
   "title": "Signal Level",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dBFS" } },
   "targets": [
    { "expr": "dBFS_signal_level{}", "legendFormat": "{{freq}}" }
   ]
  }
 ]
}